#!/usr/bin/env bash
# a bash script to print in fizzbuzz from 1 to 100

for i in {1..100};do
    ((rem1=i % 3))
    ((rem2=i % 5))

    if [ "$rem1" -eq 0 ] && [ "$rem2" -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ "$rem1" -eq 0 ]
    then
	echo "Fizz"
    elif [ "$rem2" -eq 0 ]
    then
	echo "Buzz"
    else
	echo $i
    fi
done
