#!/usr/bin/env bash
# A bash script to mimick clock funcitonality

h=0

while [ $h -le 12 ];do
      echo "Hour: "$h
      m=0
      while [ $m -lt 60 ]; do
      	    echo $m
	    ((m+=1))
      done
      ((h+=1))
done
