#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the
# below requirement:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker (use sed and transfer file content)

cp /etc/hosts ./hosts.new

echo "127.0.0.2 localhost" >> hosts.new
echo "8.8.8.8 facebook.com" >> hosts.new

cp -f ./hosts.new /etc/hosts
