#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the
# below requirement:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker (use sed and transfer file content)

cp /etc/hosts ./hosts.new

localhost_exitsts="$(grep -c '[^-]localhost' hosts.new)"
facebook_exists="$(grep -c facebook hosts.new)"

# if localhost is already in the file and not ipv6 then we
# replace it otherwice we assume we have a # and create a
# localhost info before the #
if [ "$localhost_exitsts" -ge 1 ]
then
    sed -i 's/127...... localhost/127.0.0.2 localhost/1' hosts.new
else
    sed -i 's/#/127.0.0.2 localhost\n\n#/1' hosts.new
fi

# for facebook, we also check to see whether it exists and act accordingly
if [ "$facebook_exists" -ge 1 ]
then
    sed -i 's/....... facebook/8.8.8.8 facebook/1' hosts.new
    echo "fb"
else
    sed -i 's/[^-]localhost/ localhost\n8.8.8.8 facebook.com/1' hosts.new
fi

cp -f ./hosts.new /etc/hosts
